#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/src"
DIST="$ROOT/dist"
CATALOG="$ROOT/catalog"

rm -rf "$DIST"
mkdir -p "$DIST" "$CATALOG"

declare -a OPENCLAW_ROWS=()
declare -a ZIP_ROWS=()

for skill_dir in "$SRC"/*; do
  [ -d "$skill_dir" ] || continue
  skill="$(basename "$skill_dir")"
  base="$skill_dir/base"
  body="$base/BODY.md"
  overlays="$skill_dir/overlays"

  if [ ! -f "$body" ]; then
    echo "Missing BODY.md for $skill" >&2
    exit 1
  fi

  for target_dir in "$overlays"/*; do
    [ -d "$target_dir" ] || continue
    target="$(basename "$target_dir")"
    frontmatter="$target_dir/frontmatter.yml"

    if [ ! -f "$frontmatter" ]; then
      echo "Missing frontmatter for $skill/$target" >&2
      exit 1
    fi

    version="$(awk -F': *' '/^version:/{print $2; exit}' "$frontmatter" | tr -d '"' | tr -d "'" || true)"

    out="$DIST/$skill/$target/$skill"
    mkdir -p "$out"

    {
      echo "---"
      cat "$frontmatter"
      echo "---"
      echo
      cat "$body"
    } > "$out/SKILL.md"

    for folder in references scripts assets; do
      if [ -d "$base/$folder" ]; then
        cp -R "$base/$folder" "$out/$folder"
      fi
    done

    if [ -d "$target_dir/files" ]; then
      cp -R "$target_dir/files/." "$out/"
    fi

    if [ "$target" = "openclaw" ]; then
      OPENCLAW_ROWS+=("| $skill | openclaw | clawhub install paperzilla |")
    else
      zip_name="${skill}-${target}.zip"
      if [ -n "$version" ]; then
        zip_name="${skill}-${target}-v${version}.zip"
      fi
      zip_path="$DIST/$zip_name"
      (
        cd "$DIST/$skill/$target"
        zip -qr "$zip_path" "$skill"
      )
      ZIP_ROWS+=("| $skill | $target | [$zip_name](../dist/$zip_name) |")
    fi
  done
done

{
  echo "# Skill Downloads"
  echo
  echo "This file is generated by tools/build-distributions.sh."
  echo
  echo "## OpenClaw"
  echo
  echo "| Skill | Target | Install |"
  echo "|---|---|---|"
  for row in "${OPENCLAW_ROWS[@]}"; do
    echo "$row"
  done
  echo
  echo "## Direct ZIP downloads (other targets)"
  echo
  echo "| Skill | Target | Download |"
  echo "|---|---|---|"
  for row in "${ZIP_ROWS[@]}"; do
    echo "$row"
  done
} > "$CATALOG/downloads.md"

echo "Built distributions in $DIST"
echo "Updated catalog at $CATALOG/downloads.md"
